AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  todo-app

  Sample SAM Template for todo-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900

Resources:
  TodosRamboTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: TodosRamboTable
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  TodosAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: TodosAPI
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PATCH,OPTIONS,DELETE'"
        AllowHeaders: "'content-type,authorization'"
        AllowOrigin: "'*'"
        AllowCredentials: "'*'"
      TracingEnabled: true
      MethodSettings:
        - HttpMethod: "*"
          ResourcePath: "/*"
          MetricsEnabled: true
          DataTraceEnabled: true

  GetTodoFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "ES2022"
        Sourcemap: true
        EntryPoints:
          - lambdas/get-todo.ts
    Properties:
      FunctionName: GetTodoFunction
      CodeUri: app/src/
      Handler: lambdas/get-todo.handler
      Runtime: nodejs18.x
      Description: Function used to get a todo
      Architectures:
        - arm64
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource:
                - !GetAtt TodosRamboTable.Arn
      Events:
        GetTodoEvent:
          Type: Api
          Properties:
            RestApiId: !Ref TodosAPI
            Path: /todos/{id}
            Method: get

  CreateTodoFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "ES2022"
        Sourcemap: true
        EntryPoints:
          - lambdas/post-todo.ts
    Properties:
      FunctionName: CreateTodoFunction
      CodeUri: app/src/
      Handler: lambdas/post-todo.handler
      Runtime: nodejs18.x
      Description: Function used to get a todo
      Architectures:
        - arm64
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource:
                - !GetAtt TodosRamboTable.Arn
      Events:
        CreateTodoEvent:
          Type: Api
          Properties:
            RestApiId: !Ref TodosAPI
            Path: /todos
            Method: post  

  UpdateTodoFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "ES2022"
        Sourcemap: true
        EntryPoints:
          - lambdas/update-todo.ts
    Properties:
      FunctionName: UpdateTodoFunction
      CodeUri: app/src/
      Handler: lambdas/update-todo.handler
      Runtime: nodejs18.x
      Description: Function used to update a todo
      Architectures:
        - arm64
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
              Resource:
                - !GetAtt TodosRamboTable.Arn
      Events:
        CreateTodoEvent:
          Type: Api
          Properties:
            RestApiId: !Ref TodosAPI
            Path: /todos/{id}
            Method: put

  DeleteTodoFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "ES2022"
        Sourcemap: true
        EntryPoints:
          - lambdas/delete-todo.ts
    Properties:
      FunctionName: DeleteTodoFunction
      CodeUri: app/src/
      Handler: lambdas/delete-todo.handler
      Runtime: nodejs18.x
      Description: Function used to delete a todo
      Architectures:
        - arm64
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DeleteItem
              Resource:
                - !GetAtt TodosRamboTable.Arn
      Events:
        DeleteTodoEvent:
          Type: Api
          Properties:
            RestApiId: !Ref TodosAPI
            Path: /todos/{id}
            Method: delete 
            
Outputs:
  TodosApi:
    Description: "API Gateway endpoint URL for Prod stage for Todos function"
    Value: !Sub "https://${TodosAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/todos/"
